Asp.NetCoreBestPractices.Web/Models/ErrorViewModel.cs
using System;

namespace Asp.NetCoreBestPractices.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Asp.NetCoreBestPractices.Web/Controllers/CategoriesController.cs
using Asp.NetCoreBestPractices.Core.Models;
using Asp.NetCoreBestPractices.Core.Services;
using Asp.NetCoreBestPractices.Web.ApiService;
using Asp.NetCoreBestPractices.Web.DTOs;
using Asp.NetCoreBestPractices.Web.Filters;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Asp.NetCoreBestPractices.Web.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly CategoryApiService _categoryApiService;
        private readonly IMapper _mapper;
        private readonly ICategoryService _categoryService;
        public CategoriesController(ICategoryService categoryService,IMapper mapper,CategoryApiService categoryApiService)
        {
            _mapper = mapper;
            _categoryService = categoryService;
            _categoryApiService = categoryApiService;
        }


        public async Task<IActionResult> Index()
        {
            var categories = await _categoryApiService.GetAllAsync();
            return View(_mapper.Map<IEnumerable<CategoryDto>>(categories));
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CategoryDto categoryDto)
        {
            await _categoryApiService.AddAsync(categoryDto);
            return RedirectToAction("Index");
                
        }

        public async Task<IActionResult> Update(int id)
        {
            var category = await _categoryApiService.GetByIdAsync(id);
            return View (_mapper.Map<CategoryDto>(category));
        
        }
        [HttpPost]
        public async Task<IActionResult> Update(CategoryDto categoryDto)
        {
            
        await _categoryApiService.Update(categoryDto);
            return RedirectToAction("Index");
        
        }
        [ServiceFilter(typeof(CategoryNotFoundFilter))]
        public IActionResult Delete(int id)
        {
           var deleteCategory =  _categoryService.GetByIdAsync(id).Result;
            _categoryService.Remove(deleteCategory);
            return RedirectToAction("Index");
        }
    }
}

Asp.NetCoreBestPractices.Web/Controllers/HomeController.cs
using Asp.NetCoreBestPractices.Web.DTOs;
using Asp.NetCoreBestPractices.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Asp.NetCoreBestPractices.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error(ErrorDto errorDto)
        {
            return View(errorDto);
        }
    }
}

Asp.NetCoreBestPractices.Web/Controllers/ProductController.cs
using Asp.NetCoreBestPractices.Core.Models;
using Asp.NetCoreBestPractices.Core.Services;
using Asp.NetCoreBestPractices.Web.DTOs;
using Asp.NetCoreBestPractices.Web.Filters;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Asp.NetCoreBestPractices.Web.Controllers
{
    public class ProductController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IProductService _productService;

        public ProductController(IProductService productService, IMapper mapper)
        {
            _mapper = mapper;
            _productService = productService;
        }
        public async Task<IActionResult> Index()
        {
            var products = await _productService.GetAllAsync();
            return View(_mapper.Map<IEnumerable<ProductDto>>(products));
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ProductDto productDto)
        {
            var newProduct = await _productService.AddAsync(_mapper.Map<Product>(productDto));
            return RedirectToAction("Index");

        }
        public async Task<IActionResult> Update(int id)
        {
            var product = await _productService.GetByIdAsync(id);
            return View(_mapper.Map<ProductDto>(product));
        }
        [HttpPost]
        public IActionResult Update(ProductDto productDto)
        {
            var newProduct = _mapper.Map<Product>(productDto);
            _productService.Update(newProduct);
            return RedirectToAction("Index");
        }

        [ServiceFilter(typeof(ProductNotFoundFilter))]
        public IActionResult Delete(int id)
        {
            var deleteProduct = _productService.GetByIdAsync(id).Result;
            _productService.Remove(deleteProduct);
            return RedirectToAction("Index");
        }
        
    }
}

Asp.NetCoreBestPractices.Web/Views/Categories/Create.cshtml
@model CategoryDto
@{    
    ViewData["Title"]= "Create";
}
<h1>Add Category</h1>
<div class="row">
    <div class="col-md-4"></div>

    <form asp-action="Create">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="custom-control-label"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name"></span>
            <div class="form-group">
                <input type="submit" value="Add" class="btn-primary" />

            </div>
        </div>
    </form>
    
</div>

Asp.NetCoreBestPractices.Web/Views/Categories/Index.cshtml
@model IEnumerable<CategoryDto>

@{
    ViewData["Title"] = "Index";
}


<h1>Categories</h1>
<a class="btn btn-primary mb-3" asp-action="Create">Add Category</a>
<table class="table table-bordered">
    <thead>

        <tr>

            <th> Id </th>
            <th>Name</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>@item.Id</td>
            <td>@item.Name</td>
            <td ><a asp-action="Update" asp-route-id="@item.Id">Update</a></td>
            <td><a asp-action="Delete" asp-route-id="@item.Id">Delete</a></td>
        </tr>
        }
    </tbody>

</table>

Asp.NetCoreBestPractices.Web/Views/Categories/Update.cshtml
@model CategoryDto
@{
    ViewData["Title"] = "Update";
}
<h1>Update Category</h1>
<div class="row">
    <div class="col-md-4"></div>

    <form asp-action="Update">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name">Category Name:</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Update" class="btn-primary" />


        </div>
    </form>

</div>

Asp.NetCoreBestPractices.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Asp.NetCoreBestPractices.Web/Views/Product/Create.cshtml
@model ProductDto 
@{
    ViewData["Title"] = "Create";
}
<h1>Create Product</h1>
<div class="row">
    <div class="col-md-4"></div>
    <form asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name">Product Name:</label>
            <input asp-for="Name" class="form-control" />
            <label asp-for="Stock">Stock:</label>
            <input asp-for="Stock" class="form-control" />
            <label asp-for="Price">Price:</label>
            <input asp-for="Price" class="form-control" />
            <label asp-for="CategoryId">CategoryId</label>
            <input asp-for="CategoryId" class="form-control" />



        </div>
        <div class="form-group">
            <input type="submit" value="Create" class="btn-primary" />
        </div>

    </form>

</div>

Asp.NetCoreBestPractices.Web/Views/Product/Index.cshtml
@model IEnumerable<ProductDto>
@{
    ViewData["Title"] = "Index";
}
<h1>Products</h1>
<a class="btn btn-primary mb-3" asp-action="Create">Add Category</a>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Price</th>
            <th>Stock</th>
            <th>Category</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Price</td>
                <td>@item.Stock</td>
                <td>@item.CategoryId</td>
                <td><a asp-action="Update" asp-route-id="@item.Id">Update</a></td>
                <td><a asp-action="Delete" asp-route-id="@item.Id">Delete</a></td>
            </tr>
        }
    </tbody>




</table>

Asp.NetCoreBestPractices.Web/Views/Product/Update.cshtml
@model ProductDto
@{
    ViewData["Title"] = "Update";
}
<h1>Update Product</h1>
<div class="row">
    <div class="col-md-4"></div>
    <form asp-action="Update">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name">Product Name:</label>
            <input asp-for="Name" class="form-control" />
            <label asp-for="Stock">Stock:</label>
            <input asp-for="Stock" class="form-control" />
            <label asp-for="Price">Price:</label>
            <input asp-for="Price" class="form-control" />
            <label asp-for="CategoryId">CategoryId</label>
            <input asp-for="CategoryId" class="form-control" />



        </div>
        <div class="form-group">
            <input type="submit" value="Update" class="btn-primary" />
        </div>

    </form>

</div>

Asp.NetCoreBestPractices.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Asp.NetCoreBestPractices.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Asp.NetCoreBestPractices.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item"> <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a> </li>
                        <li class="nav-item"> <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a> </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Asp.NetCoreBestPractices.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <partial name="_ValidationScriptsPartial"/>
    @RenderSection("Scripts", required: false)
</body>
</html>